### ISSUE TITLE
Block structure mismatch on ClickHouseDatabaseMetaData.getFunctions

### ISSUE THREAD

**Issue by kassak** [ClickHouse/clickhouse-jdbc#938] opened 2022-05-16 13:21 UTC
Hi!
Our tests have caught the problem in DatabaseMetaData
The driver is 0.3.2-patch9
```
Code: 49, e.displayText() = DB::Exception: Block structure mismatch in Pipe::unitePipes stream: different number of columns:
FUNCTION_CAT Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), FUNCTION_SCHEM String Const(size = 0, String(size = 1)), FUNCTION_NAME String String(size = 0), REMARKS String String(size = 0), FUNCTION_TYPE UInt8 UInt8(size = 0), SPECIFIC_NAME String String(size = 0), NULL Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), 'system' String Const(size = 0, String(size = 1)), 'case-sensistive table function' String Const(size = 0, String(size = 1)), 2 UInt8 Const(size = 0, UInt8(size = 1))
FUNCTION_CAT Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), FUNCTION_SCHEM String Const(size = 0, String(size = 1)), FUNCTION_NAME String String(size = 0), REMARKS String String(size = 0), FUNCTION_TYPE UInt8 UInt8(size = 0), SPECIFIC_NAME String String(size = 0), NULL Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), 'system' String Const(size = 0, String(size = 1)), 1 UInt8 Const(size = 0, UInt8(size = 1)) (version 21.6.5.37 (official build))
, server ClickHouseNode(addr=http:localhost/<unresolved>:8126, db=default)@-279499002
java.sql.SQLException: Code: 49, e.displayText() = DB::Exception: Block structure mismatch in Pipe::unitePipes stream: different number of columns:
FUNCTION_CAT Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), FUNCTION_SCHEM String Const(size = 0, String(size = 1)), FUNCTION_NAME String String(size = 0), REMARKS String String(size = 0), FUNCTION_TYPE UInt8 UInt8(size = 0), SPECIFIC_NAME String String(size = 0), NULL Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), 'system' String Const(size = 0, String(size = 1)), 'case-sensistive table function' String Const(size = 0, String(size = 1)), 2 UInt8 Const(size = 0, UInt8(size = 1))
FUNCTION_CAT Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), FUNCTION_SCHEM String Const(size = 0, String(size = 1)), FUNCTION_NAME String String(size = 0), REMARKS String String(size = 0), FUNCTION_TYPE UInt8 UInt8(size = 0), SPECIFIC_NAME String String(size = 0), NULL Nullable(Nothing) Const(size = 0, Nullable(size = 1, Nothing(size = 1), UInt8(size = 1))), 'system' String Const(size = 0, String(size = 1)), 1 UInt8 Const(size = 0, UInt8(size = 1)) (version 21.6.5.37 (official build))
, server ClickHouseNode(addr=http:localhost/<unresolved>:8126, db=default)@-279499002
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:55)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:70)
	at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.query(ClickHouseDatabaseMetaData.java:74)
	at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.query(ClickHouseDatabaseMetaData.java:52)
	at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.getFunctions(ClickHouseDatabaseMetaData.java:1272)
```

Difference is 'case-sensistive table function'

**Comment by zhicwu** [comment] 2022-05-16 14:08
Thanks @kassak but I'm not sure what the issue is. Could you elaborate? Does the same issue exist on newer version of ClickHouse like 22.3? If you can share the test, I can add it for regression.

**Comment by kassak** [comment] 2022-05-20 08:50
The issue is the exception thrown on ClickHouseDatabaseMetaData.getFunctions call :)
Sorry the test is the part of our integration tests. I think just calling that method is enough to fail.
I've checked, that works on 22 server

**Comment by zhicwu** [comment] 2022-05-20 09:06
Thanks @kassak. I hope it's not related to the typo, which has been fixed on develop branch. Will try to reproduce the issue on 21.6.

**Closed** 2022-06-20 23:03 UTC
Labels: bug
