### ISSUE TITLE
The user name and password are printed in the debug level log

### ISSUE THREAD

**Issue by huldarchen** [ClickHouse/clickhouse-jdbc#522] opened 2020-11-20 13:24 UTC
ClickHouseStatementImpl：L578。

**Comment by TTcheng** [comment] 2020-12-23 08:24
![image](https://user-images.githubusercontent.com/19683420/102975239-b27eb480-453a-11eb-9056-d3ae775de026.png)
I found the same issue occured in my project logs,It seems like that the request uses plain text password, this is extremely dangerous

**Comment by enqueue** [comment] 2021-01-19 06:49
I see a couple of short-term, i.e. 0.2.5 target, options here. What are your opinions?

1. Hard-coded RegExp filter which can be used in `ClickhouseStatementImpl`, and perhaps one or five more places
2. Try to find a way to install RegExp filter somehow. I don't think there is a way built-into SLF4J without interfering with users' implementation settings, though. I don't like the idea of introducing something like `ClickHouseLogger.getLogger()` (which would include such a filter) and forcing all developers to use that.
3. Use [HTTP Basic Auth](https://clickhouse.tech/docs/en/interfaces/http) and get rid of these query parameters. I am unsure because original driver authors chose otherwise. Do you see any compatibility issues?

**Comment by zhicwu** [comment] 2021-01-19 07:35
> I see a couple of short-term, i.e. 0.2.5 target, options here. What are your opinions?

Thanks @enqueue. I agree with you that the first two are not ideal, while the third is better. Actually, in a private version of ClickHouse JDBC driver, I added `authMode` setting and made basic auth as default. It was not only for security reason but also to ensure the driver works with clickhouse server(s) behind proxy like httpd/nginx/traefik. I think we should go with the third. However, we may still need to keep query parameter for older version. We can add `19.14` into [this](blob/develop/.github/workflows/build.yml#L28) and add regression test case accordingly. By the way, there'll be one or two cases failed on 19.14 ;)

@alexey-milovidov / @den-crane / @filimonov, do you have impression of why we use query parameter to pass credential instead of basic auth in http header? Any specific version of clickhouse server should be added into regression?

**Comment by filimonov** [comment] 2021-01-19 07:53
> do you have impression of why we use query parameter to pass credential instead of basic auth in http header? 

Have no idea. Basic auth is totally ok (and always was).

**Comment by zhicwu** [comment] 2021-01-20 00:42
@enqueue, I hope you don't mind that I merged PR #546 just now. Now `19.14` is added into regression. If you have docker installed, you can run tests against specific version of ClickHouse on develop branch by issue command line below:
```bash
mvn -DclickhouseVersion=19.17 clean verify
```

I think we can proceed with the change by using basic auth instead of query parameters.

**Comment by enqueue** [comment] 2021-01-24 09:41
Test plan:

| ClickHouse user setting | Property: `user` | Property: `password` | Expected result |
| ----------------------- | ---------------- | -------------------- | --------------- |
| default                 |                  |                      | Success         |
| default                 | default          |                      | Success         |
| default                 | default          | bar                  | Failure         |
| default                 |                  | bar                  | Failure         |
| default / bar           |                  | bar                  | Success         |
| default / bar           | default          | bar                  | Success         |
| foo / bar               |                  |                      | Failure         |
| foo / bar               | foo              |                      | Failure         |
| foo / bar               | foo              | baz                  | Failure         |
| foo / bar               | foo              | bar                  | Success         |
| foo / bar               |                  | bar                  | Failure         |
| foo / bar               | baz              | bar                  | Failure         |
| foo                     |                  |                      | Failure         |
| foo                     | foo              |                      | Success         |
| foo                     | foo              | bar                  | Failure         |
| foo                     | baz              |                      | Failure         |

**Comment by zhicwu** [comment] 2021-02-08 02:50
This has been fixed on develop and will be released as part of 0.2.6. With basic auth and a proxy(httpd/nginx etc.) in front of ClickHouse, you can now do lots of stuff like ActiveDirectory authentication :)

**Closed by zhicwu** 2021-02-08 02:50 UTC
Labels: bug
