### ISSUE TITLE
please debug "The Transfer-Encoding is not chunked and there is no Content-Length header for POST "

### ISSUE THREAD

**Issue by osenlin** [ClickHouse/clickhouse-jdbc#544] opened 2021-01-15 11:21 UTC
A bug can occur when writing too many bytes of single record data
```
 DB::Exception: The Transfer-Encoding is not chunked and there is no Content-Length header for POST request (version 20.12.3.3 (official build)
```
the post large data , request header ,must be set "Transfer-Encoding：chuncked"
use clickhouse4j insert same record is ok

**Comment by zhicwu** [comment] 2021-02-10 00:15
Defer to 0.3.0 so that we can fix this together with new ClickHouse client interface.

**Comment by zhicwu** [comment] 2021-03-21 14:46
Couldn't reproduce the issue at my end.

@osenlin, would you mind to share more details like what your query looks like and settings of `max_query_size`, `max_ast_elements` and `max_expanded_ast_elements`? I tried a few large queries but ended up with `Max query size exceeded` and `AST is too big`.

**Comment by den-crane** [comment] 2021-03-24 01:18
it's a bug in CH server https://github.com/ClickHouse/ClickHouse/issues/21907

related to https://github.com/ClickHouse/ClickHouse/issues/17073

**Comment by zhicwu** [comment] 2021-03-24 01:36
It's interesting that clickhouse4j will work for inserting the same record. I'd leave this open so that we can revisit when we have a new http client in `clickhouse-http-client`.

**Comment by den-crane** [comment] 2021-03-24 01:42
because clickhouse4j does not apache httpclient

**Comment by den-crane** [comment] 2021-04-03 15:01
fixed in CH https://github.com/ClickHouse/ClickHouse/pull/22322

**Closed by den-crane** 2021-04-03 15:01 UTC
Labels: bug
