### ISSUE TITLE
Error while getting column metadata

### ISSUE THREAD

**Issue by voidconductor** [ClickHouse/clickhouse-jdbc#381] opened 2019-09-02 16:36 UTC
Looks like there's typo in a column name

no column **default_expresseion** in columns list database table name type default_type default_expression

```
java.lang.RuntimeException: no column default_expresseion in columns list database table name type default_type default_expression
	at ru.yandex.clickhouse.response.ClickHouseResultSet.asColNum(ClickHouseResultSet.java:616)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getString(ClickHouseResultSet.java:251)
	at ru.yandex.clickhouse.ClickHouseDatabaseMetadata.getColumns(ClickHouseDatabaseMetadata.java:863)
	at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:227)
	at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:227)
	at scalikejdbc.DBConnection.getAllColumns(DBConnection.scala:426)
	at scalikejdbc.DBConnection.getAllColumns$(DBConnection.scala:414)
	at scalikejdbc.NamedDB.getAllColumns(NamedDB.scala:20)
	at scalikejdbc.DBConnection.$anonfun$getColumnNames$2(DBConnection.scala:438)
	at scala.Option.map(Option.scala:163)
	at scalikejdbc.DBConnection.$anonfun$getColumnNames$1(DBConnection.scala:436)
	at scalikejdbc.DBConnection.$anonfun$readOnlyWithConnection$1(DBConnection.scala:221)
	at scalikejdbc.DBConnection.$anonfun$readOnly$1(DBConnection.scala:210)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:18)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16)
	at scalikejdbc.NamedDB.using(NamedDB.scala:20)
	at scalikejdbc.DBConnection.readOnly(DBConnection.scala:210)
	at scalikejdbc.DBConnection.readOnly$(DBConnection.scala:209)
	at scalikejdbc.NamedDB.readOnly(NamedDB.scala:20)
	at scalikejdbc.DBConnection.readOnlyWithConnection(DBConnection.scala:221)
	at scalikejdbc.DBConnection.readOnlyWithConnection$(DBConnection.scala:220)
	at scalikejdbc.NamedDB.readOnlyWithConnection(NamedDB.scala:20)
	at scalikejdbc.DBConnection.getColumnNames(DBConnection.scala:434)
	at scalikejdbc.DBConnection.getColumnNames$(DBConnection.scala:433)
	at scalikejdbc.NamedDB.getColumnNames(NamedDB.scala:20)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxSupport.$anonfun$columns$1(SQLSyntaxSupportFeature.scala:157)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:907)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxSupport.columns(SQLSyntaxSupportFeature.scala:157)
	at scalikejdbc.SQLSyntaxSupportFeature$SQLSyntaxSupport.columns$(SQLSyntaxSupportFeature.scala:154)

```

**Comment by enqueue** [comment] 2019-09-02 16:38
Yes, sorry about this regression due to a late change. I filed PR #377 to fix this.

**Comment by Augello** [comment] 2019-12-02 09:15
The typo is in version 0.2 of the driver in maven repository.

Cloning the project I found that the error is fixed in the code (ClickHouseDatabaseMetadata  line 863 is fixed), but using a java decompiler (JD) on the maven jar, I fount that in the same line there is the misspelled string.
The git repository is misaligned with the maven package on maven central.

I hope this helps.
Regards.

**Comment by fabiorhs** [comment] 2020-06-22 15:21
We have the same issue on a very recent version (7.1.1.202006211844) on windows on a single table (yet we cannot understand why with another version - 7.1.0.202005311732, still windows and on the same table - we are not experiencing it).
Anyway, looking forward to have this fixed.

**Comment by zhicwu** [comment] 2021-01-08 05:09
This has been fixed. Please upgrade your clickhouse jdbc driver to `0.2.3` or above.

**Closed by zhicwu** 2021-01-08 05:09 UTC
Labels: bug
